### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by klaussilveira** [CHH/heroku-buildpack-php#167]
Has the support for this buildpack been dropped?

**Comment by stof** [comment]
@CHH and me don't really have time to maintain this project (he already gave me access so that I could help a little more than he did, but I never commited to take the lead of the project because of missing resources for that).
And given that heroku released an official PHP buildpack which is actively updated, I strongly advise using the official buildpack instead.

**Comment by CHH** [comment]
Problem is that the tool that I used to build all the binaries (vulcan) isn't supported by Heroku anymore, and I think therefore we can't update the binaries anymore. They have made [a new tool](https://github.com/kennethreitz/bob-builder) and it would be too much work to migrate the build process.

I'm in contact with the maintainer of the official Heroku PHP build pack @dzuelke and some of the ideas of this buildpack live on in the official one.

**Comment by dzuelke** [comment]
Is there anything in particular you are missing in the official buildpack, @klaussilveira ?

**Comment by Soulou** [comment]
We are actually maintaining a fork of this buildpack: https://github.com/Scalingo/appsdeck-buildpack-php, feel free to use it. We'd like to provide better framework compatibility that what Heroku's doing.
